dms/dms/urls.py
from django.shortcuts import render, HttpResponse,redirect
from django.urls import reverse_lazy ,include,re_path,path
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    # GET /
    path('', include('jogos.urls', namespace='jogos')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dms/jogos/urls.py
from jogos.views import  Index_Template,Competicoes_Views
from jogos.views import   Jogos_Alterar

from jogos.views import  Jogo_Add_Competicao,Jogo_Add_Jogador

from django.shortcuts import render, HttpResponse,redirect
from django.urls import reverse_lazy ,include,re_path,path
from django.conf.urls.static import static
from django.conf import settings
#from django.conf.urls import url



app_name = 'jogos'


urlpatterns = [
    # GET /
    path('', Index_Template.as_view(), name="home"),
    path('competicao/<slug:slug>', Competicoes_Views.as_view(), name="competicao"),
    path('add/competicao',Jogo_Add_Competicao.as_view(), name='add_competicao'),

    path('add/jogador',Jogo_Add_Jogador.as_view(), name='add_jogador'),

    path('jogos/alterar/',Jogos_Alterar.as_view(), name='alterar_jogos'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dms/jogos/models.py
from django.db import models
from datetime import datetime, date
from django.urls import reverse
from autoslug import AutoSlugField

# Create your models here.
class Competicao(models.Model):
     
    STATUS = (
    ('0', 'Encerrado'),
    ('1', 'Em Andamento'), 
    ('2', 'Em Espera'), )  
 
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=135, verbose_name='Nome')
    local = models.CharField(null =False,max_length=255, verbose_name='Local')
    slug = AutoSlugField(max_length=255,unique=True,populate_from='nome',verbose_name='slug',editable=False)

    data = models.CharField(null=True,blank=True,max_length=135, verbose_name='Data')
    hora = models.CharField(null=True,blank=True,max_length=135, verbose_name='Hora da Partida')
    status = models.CharField(default='1', null=True,blank=True,max_length=35,choices=STATUS)
    def __str__(self):
        
            return self.nome
    def get_absolute_url(self):    
           return reverse('jogos:competicao', args=[str(self.slug)])
    def get_rota(self):
            return reverse("jogos:competicao", kwargs={"slug": self.slug})
        
    class Meta:
       db_table = u'tipo'
       verbose_name = 'Competicao'
       verbose_name_plural = 'Competicao'
       
       
class Jogadores(models.Model):
    TENTATIVAS = (
    ('1', '1'),
    ('2', '2'), 
    ('3', '3'), )  
    id = models.AutoField(primary_key=True)
    
    nome = models.CharField(null =False,max_length=255, verbose_name='Nome Completo ')
    
    competicao = models.ForeignKey(Competicao, on_delete=models.CASCADE,related_name='Competicao')
    tempo = models.CharField(null=True,blank=True,max_length=135, verbose_name='Tempo em Segundos, Distancia em Metros')
    distancia = models.CharField(null=True,blank=True,max_length=135, verbose_name='Tempo em Segundos, Distancia em Metros')
    tentativas = models.CharField(default='1', null=True,blank=True,max_length=5,choices=TENTATIVAS,verbose_name='Tentativa ')
   

    created = models.DateField(auto_now=True)
    updated = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.nome
 
    def get_nome(self):
           return self.nome
       
       
    class Meta:
        db_table = u'jogos'
        verbose_name = 'Jogador'
        verbose_name_plural = 'Jogadores'
        ordering = ['tempo']

dms/jogos/forms.py
from django import forms
from jogos.models import Jogadores,Competicao

class Jogos_Form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(Jogos_Form, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({'class': 'form-control edit-jog',}) 
    class Meta:
        model = Jogadores
        fields = ['nome','competicao','tempo','distancia','tentativas']
        labels = {
        'nome':'Nome:',
        'competicao':'Competicao:',
        'tempo':'Tempo:',
        'distancia':'Distancia:',
        'tentativas':'Tentativa:'
 
       } 
class Competicao_Form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(Competicao_Form, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({'class': 'form-control edit-comp ',}) 
    class Meta:
        model = Competicao
        fields = ['nome','local','data','hora','status']
        labels = {
        'nome':'Nome:',
        'local':'Local:',
        'data':'Data:',
        'hora':'Hora:',
        'status':'Status:'
 
       } 

dms/jogos/views.py
from django.views.generic import TemplateView, ListView
from django.shortcuts import render, HttpResponse,redirect
from django.urls import reverse_lazy ,path

from jogos.models import Jogadores,Competicao
from jogos.forms import Jogos_Form,Competicao_Form

# Create your views here.

class Index_Template(ListView):
    template_name = 'jogos/home.html'
    def get(self, request, *args, **kwargs):
   
       model = Jogadores,Competicao
       tipo = request.session.get('tipo')
       print(tipo)
       return render(request,self.template_name ,{
        'competicoes' : Competicao.objects.filter(status= 1),
        'competicoes_encerrada' : Competicao.objects.filter(status= 0),
        'listar_todos':Jogadores.objects.all(),
        'listar_encerrados': Jogadores.objects.order_by("-competicao")[:12],
        #'banner_footer':   Website_Banner.objects.filter(local="footer"),
    
       })

class Competicoes_Views(ListView):
    
    template_name = 'jogos/competicao.html'
    def get(self, request, *args,slug, **kwargs):
   
       model = Jogadores,Competicao
       tipo = Competicao.objects.filter(slug=slug)
       if Competicao.objects.filter(slug=slug).exists():
           for i in tipo:
              inscrito = i.id
         
         #tipo = request.session.get('tipo')
           return render(request,self.template_name ,{
        'competicoes' : Competicao.objects.filter(slug=slug),
        'ranquim' : Jogadores.objects.filter(competicao=inscrito),
        'listar_todos': Jogadores.objects.filter(competicao=inscrito),
        'listar_encerrados': Jogadores.objects.order_by("-competicao")[:12],
        #'banner_footer':   Website_Banner.objects.filter(local="footer"),
    
           })
       return redirect("jogos:home")
     
class Jogo_Add_Jogador(ListView):
    
    template_name = 'jogos/add_competidor.html'
    model= Jogadores
    
    def get(self, request, *args, **kwargs):   
        
        form = Jogos_Form()
        return render(request,self.template_name ,{
        'form' :form,
        })
        
    def post(self, request, *args, **kwargs):
     if request.method == "POST":
            
        form = Jogos_Form(request.POST)
        if form.is_valid():
            model= Jogadores
            id = request.POST["competicao"]
            print(id)
            if Competicao.objects.filter(id= id).filter(status = 0):
                   return render(request,self.template_name ,{
                  'form' :form,
                  'msg': "Competicao encerrada"
                   })
            else:
             form.save()
             return render(request,self.template_name ,{
             'form' :form,
             'msg': "Competidor salvo"
             })
        else:
            return render(request,self.template_name ,{
            'form' :form,
            'msg': "Erro ao salvar"
            })
            
        return redirect("jogos:add_jogos")

class Jogo_Add_Competicao(ListView):
    
    template_name = 'jogos/add_competicao.html'
    model= Competicao
    
    def get(self, request, *args, **kwargs):   
        
        form = Competicao_Form
        return render(request,self.template_name ,{
        'form' :form,
        'competicoes' : Competicao.objects.all(),
        'competicoes_encerrada' : Competicao.objects.filter(status= 0),
        })
        
    def post(self, request, *args, **kwargs):
     if request.method == "POST":
            
        form = Competicao_Form(request.POST)
        if form.is_valid():
            model= Competicao
            
            form.save()
            return render(request,self.template_name ,{
             'form' :form,
             'msg': "Competicao salva salvo",
            'competicoes' : Competicao.objects.all(),
            'competicoes_encerrada' : Competicao.objects.filter(status= 0),
             })
        else:
            return render(request,self.template_name ,{
            'form' :form,
            'msg': "Erro ao salvar",
            'competicoes' : Competicao.objects.all(),
            'competicoes_encerrada' : Competicao.objects.filter(status= 0),
            })
            
     return redirect("jogos:add_competicao")

class Jogos_Alterar(ListView):
    template_name = 'jogos/usuario/usuario.html'
    model = Jogadores,Competicao
    
    def get(self, request, *args, **kwargs):
      
        if request.session.get('user_id'):
            
          model = Jogadores,Competicao
          id = request.session.get('id')
          
          if Jogadores.objects.filter(id = id).exists():
            jogo = Jogadores.objects.get(id=id)
            jogoform=Jogadores(instance=jogo)
                        
            return render(request,self.template_name ,{
                'jogoform':jogoform,     
       
            })
          else:
           return redirect("jogos:home")
        else:
         return redirect("jogos:home")
    
    def post(self, request, *args, **kwargs):
        if request.method == "POST":
           jogo = Jogadores.objects.get(id=id)
           
           form = Jogos_Form(request.POST,request.FILES,instance=jogo)
           
           if form.is_valid():
                form.save()
                  # instance = form
                user = request.session.get('home')
                return redirect('jogos:home')

dms/jogos/templates/jogos/add_competicao.html
{% extends "jogos/layout_base/base.html" %}
{% load static %}

{% block conteudo %}

<div class="container" >
  <div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4" >
    {% if msg %} {{msg}} {%endif%}
    <div id="alerta"></div>
    <form method="POST" >
     
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group col-12 ">
          <label class="label-form">{{ field.label }}</label>
          {{ field }}
        </div>
        {% endfor %}
        <br>
        <input type="submit" value="Adicionar" class="btn"/>
        
      <form>
        <a href="{% url 'jogos:home' %}">Voltar</a>
  </div> <!-- end col -->
  <div class="col-md-4"></div>
  </div>
  <div class="col-md-12">
    <h1>Competicao Ativas</h1>
    {% for competicao in competicoes %}
    <p>
      <a href="{{ competicao.get_absolute_url }}">Competicao: {{ competicao.nome }} </a>

    </p>
    {% endfor %}
    
  </div><!-- end md-12 -->
  <div class="col-md-12">
    <h1>Competicao Encerradas</h1>
    {% for competicao in competicoes_encerrada %}
    <p>
      <a href="{{ competicao.get_absolute_url }}">Competicao: {{ competicao.nome }} </a>

    </p>
    {% endfor %}
    
  </div><!-- end md-12 -->
</div> <!-- end container -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> 

<script>
   
  $(document).ready(function () {
      
   const alertBox = document.getElementById('alerta')
   $("#form").submit(function (e) {
           e.preventDefault();
           
           var serializedData = $(this).serialize();
           $.ajax({
               type: 'POST',
               url: "{% url 'jogos:add_competicao' %}",
               data: serializedData,
               success: function (response) {
                //
                alertBox.innerHTML = `<div class="alert alert-sucess alert-dismissible fade show" role="alert">
                  <strong>Salvo</strong>
                  <button type="button" class="btn-close" data-bs-dismiss="alert"aria-label="Close"></button></div>`
               }
                   
               },
               error: function (response) {
                   alertBox.innerHTML = `<div class="alert alert-warning alert-dismissible fade show" role="alert">
                                         <strong>Erro...</strong> erro..!.
                                         <button type="button" class="btn-close" data-bs-dismiss="alert"aria-label="Close"></button></div>`
                                      }
           })
       })

   })

</script>

{% endblock conteudo %}

dms/jogos/templates/jogos/add_competidor.html
{% extends "jogos/layout_base/base.html" %}
{% load static %}

{% block conteudo %}

<div class="container" >
  <div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4" >
    {% if msg %} {{msg}} {%endif%}
    <div id="alerta"></div>
    <form method="POST" >
     
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group col-12 ">
          <label class="label-form">{{ field.label }}</label>
          {{ field }}
        </div>
        {% endfor %}
        <br>
        <input type="submit" value="Adicionar" class="btn"/>
        
      <form>
        <a href="{% url 'jogos:home' %}">Voltar</a>
  </div> <!-- end col -->
  <div class="col-md-4"></div>
  </div>
</div> <!-- end container -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> 

<script>
   
  $(document).ready(function () {
      
   const alertBox = document.getElementById('alerta')
   $("#form").submit(function (e) {
           e.preventDefault();
           
           var serializedData = $(this).serialize();
           $.ajax({
               type: 'POST',
               url: "{% url 'jogos:add_jogador' %}",
               data: serializedData,
               success: function (response) {
                //
                alertBox.innerHTML = `<div class="alert alert-sucess alert-dismissible fade show" role="alert">
                  <strong>Salvo</strong>
                  <button type="button" class="btn-close" data-bs-dismiss="alert"aria-label="Close"></button></div>`
               }
                   
               },
               error: function (response) {
                   alertBox.innerHTML = `<div class="alert alert-warning alert-dismissible fade show" role="alert">
                                         <strong>Erro...</strong> erro..!.
                                         <button type="button" class="btn-close" data-bs-dismiss="alert"aria-label="Close"></button></div>`
                                      }
           })
       })

   })

</script>

{% endblock conteudo %}

dms/jogos/templates/jogos/alterar_jogos.html
{% extends "website/layout_base/base.html" %}
{% load static %}

{% block conteudo %}

<div class="container" >
  <div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4" >
    <div id="alerta">{% if alerta %}{{ alerta }} {% endif %}</div>
    <div id="ok"></div>
    <form id="alterar" method="POST" >
     
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group col-12 ">
          <label class="label-form">{{ field.label }}</label>
          {{ field }}
        </div>
        {% endfor %}
        <input type="submit"  value="Enviar" id="enviar" />
        
      <form>

  </div> <!-- end col -->
  <div class="col-md-4"></div>
  </div>
</div> <!-- end container -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> 

<script>
   
  $(document).ready(function () {
      
   const alertBox = document.getElementById('alerta')
   $("#fale_form").submit(function (e) {
           e.preventDefault();
           alert('ok')
           var serializedData = $(this).serialize();
           $.ajax({
               type: 'POST',
               url: "{% url 'website:fale_conosco' %}",
               data: serializedData,
               success: function (response) {
                //
              var instance = JSON.parse(response["instance"]);
                    var fields = instance[0]["fields"];
                    $("#ok ").prepend(
                        `<div class="alert alert-success alert-dismissible fade show" role="alert">
                        Tudo Certo  ${fields["nome"]||""} logo Responderemos !
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         </div>`
                    )
                    $("#fale_form").fadeOut(2000);
                    $("#ok").fadeOut(10000);
               },
               error: function (response) {
                   alertBox.innerHTML = `<div class="alert alert-warning alert-dismissible fade show" role="alert">
                                         <strong>Erro...</strong> erro..!.
                                         <button type="button" class="btn-close" data-bs-dismiss="alert"aria-label="Close"></button></div>`
                                      }
           })
       })

   })

</script>

{% include "website/banners/banner-bottom.html" %}
{% endblock conteudo %}

dms/jogos/templates/jogos/competicao.html
{% extends "jogos/layout_base/base.html" %}
{% load static %}

{% block conteudo %}
  <div class="box">
    <div class="container">
        <div class="row ">
          <div class="col-md-12">
            <h1>Inscritos nesta competicao</h1>
            {% for competicao in competicoes %}
            <p>
             Competicao: {{ competicao.nome }}
            </p>
            {% endfor %}
            
          </div><!-- end md-12 -->
          <div class="col-md-12">
            {% if listar_todos %}
            {% for listar_todo in listar_todos %}
            <p>
             Nome: {{ listar_todo.nome }},   Competicao: {{ listar_todo.competicao }} ,   Tempo/Metros: {{ listar_todo.tempo }}
            </p>
            {% endfor %}
            {% endif %}
          </div><!-- end md-12 -->
          <hr>
          {% if ranquim %}
            {% for nome in ranquim %}
            <h1>Campeao:  {{ nome.nome }}<span>{{nome.distancia}}</span><span>{{nome.tempo}}</span></h1>
            {% endfor %}
            <hr>
            <h1> <a href="{% url 'jogos:add_jogador' %}">Add Competidor:</a></h1>
          {% else %}
          <hr>
          <h1> <a href="{% url 'jogos:add_jogador' %}">Add Competidor:</a></h1>
          {% endif%}
        
          <a href="{% url 'jogos:home' %}">Voltar</a>
        </div><!-- end row -->
    </div> <!-- end container -->
  </div><!--end box- -->


  {% endblock %}

dms/jogos/templates/jogos/home.html
{% extends "jogos/layout_base/base.html" %}
{% load static %}

{% block conteudo %}
  <div class="box">
    <div class="container">
        <div class="row ">
          <div class="col-md-12">
            <h1>Escolha a competicao Aberta </h1>
            {% for competicao in competicoes %}
            <p>
           <a href="{{ competicao.get_absolute_url }}">Competicao: {{ competicao.nome }} </a>
            </p>
           
            {% endfor %}
            
          </div><!-- end md-12 -->
          <div class="col-md-12">
            <hr>
            <h1>Escolha a competicao Encerrada </h1>
            {% for competicao in competicoes_encerrada %}
            
            <p><a href="{{ competicao.get_absolute_url }}">Competicao: {{ competicao.nome }} </a></p>
           
            {% endfor %}
            
          </div><!-- end md-12 -->
          <hr>
          <h1> <a href="{% url 'jogos:add_competicao' %}">Add Competicao:</a></h1>

        </div><!-- end row -->
    </div> <!-- end container -->
  </div><!--end box- -->


  {% endblock %}